### ISSUE TITLE
New tasks

### ISSUE THREAD

**Issue by MaksymTaratuta55** [ramsayinnovations/ramsay-ui#12]
@thecodeclimber, could you please add new tasks for me?

**Comment by MaksymTaratuta55** [comment]
@thecodeclimber, could you please add new tasks again?

**Comment by MaksymTaratuta55** [comment]
@thecodeclimber, could you please add new tasks again?

**Comment by thecodeclimber** [comment]
@MaksymTaratuta55 

Yes -- if not tonight, then tomorrow morning.  

Btw, in the future can you please send these requests in slack?  Thanks :).
