### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by thecodeclimber** [ramsayinnovations/ramsay-ui#17]
@MaksymTaratuta55 

We need to test all of the components that they work properly.  Can you please get working on that?

In terms of where to test it, I have two ideas:  

1. import the ramsay-ui library into a test branch of ramsay-site and test it there 
2. create a new next.js repository that we use for testing purposes and import the library into there.  

I am, though, open to alternatives.

Either way, please get started in whichever way you think is best and on Monday or Tuesday I hope to take a look at it.

Thanks and be well.

**Comment by thecodeclimber** [comment]
@MaksymTaratuta55 

Can you show me what you have done so far (without doing any more testing for the moment)?

**Comment by MaksymTaratuta55** [comment]
@thecodeclimber, could you please clarify what you mean?

**Comment by MaksymTaratuta55** [comment]
After I setted up repos,I just created a component, changed props, and then removed it. And do it with all components

**Comment by thecodeclimber** [comment]
@MaksymTaratuta55 

is there any code you can show me right now?  

If so, can you please send me a link to that code.
If not, let's close this issue and we'll worry about this later if need be.  

:)

**Comment by MaksymTaratuta55** [comment]
Here example. But it's only with one component. I need to update ramsay-ui to work with ramsay-site. And then you will be able to test it without problems

<img width="696" alt="Screenshot 2021-02-03 at 18 42 35" src="https://user-images.githubusercontent.com/29330551/106779429-a7499900-664f-11eb-9e81-257ff06d5cea.png">

<img width="608" alt="Screenshot 2021-02-03 at 18 42 55" src="https://user-images.githubusercontent.com/29330551/106779434-a9135c80-664f-11eb-8a15-55a68a1e1812.png">

**Comment by thecodeclimber** [comment]
okay - let's leave this for now and we'll test it vis-a-vis making the Contact Us page.  I just want to close out all existing issues and PR's first on Ramsay Site and then we can work on the Contact Us page.
