### ISSUE TITLE
Navbar Component

### ISSUE THREAD

**Issue by thecodeclimber** [ramsayinnovations/ramsay-ui#3]
@MaksymTaratuta55 

After we implement the typography component (#2) we need to move the Navbar component over.  I.e., this component:  https://github.com/ramsayinnovations/ramsay-site/pull/140

We should split that component into two separate components -- a `Navbar` component and a `Menu` component.  

Details to follow...

**Comment by MaksymTaratuta55** [comment]
@thecodeclimber, I am ready to start. Could you please provide details?

**Comment by thecodeclimber** [comment]
@MaksymTaratuta55 

I have done some initial work on getting these ready -- here is a link:  https://github.com/ramsayinnovations/ramsay-ui/tree/issue/%233--navbar-components

And here is a video detailing what I would like to do:  https://www.loom.com/share/eeedd5cc4b664f1888adc1d8158c1981 

Please let me know if you have any questions.  Thanks.

**Comment by MaksymTaratuta55** [comment]
@thecodeclimber, I need to create the `MenuLink` component and the `MobileNav` component, am I right?

**Comment by thecodeclimber** [comment]
@MaksymTaratuta55 

Yes to the `MenuLink` component, no to the `MobileNav` component.  The `Menu` component has a `mobile` prop -- we should use that.  

Note also, in terms of the mobile version -- we should NOT style it to look like the current mobile menu on ramsayinnovations.com.  Rather, we should use the current tailwind-ui styles -- but just a simplified version of tailwind ui -- one that only uses the links we are currently using.  I hope that makes sense.

**Comment by MaksymTaratuta55** [comment]
@thecodeclimber, could you please check my commit https://github.com/ramsayinnovations/ramsay-ui/commit/d8707c7ff5737aef858c931044f615b60bc5c568? Does it what you want?

**Comment by MaksymTaratuta55** [comment]
@thecodeclimber, could you please check my comment above?

**Comment by thecodeclimber** [comment]
@MaksymTaratuta55 

sorry -- I should have let you know that I'm looking into it.  I'm in the middle of making some changes.  Overall it is great -- thanks.

**Comment by thecodeclimber** [comment]
@MaksymTaratuta55 

Please see this video for the next steps:  https://www.loom.com/share/5260722e335c4cb2a7b8138991dd1854

Thanks.

**Comment by MaksymTaratuta55** [comment]
@thecodeclimber, updated
