### ISSUE TITLE
Hero Components

### ISSUE THREAD

**Issue by thecodeclimber** [ramsayinnovations/ramsay-ui#6]
@MaksymTaratuta55 

Hello -- I made a video about how I would like to do the hero components:  https://www.loom.com/share/81ba5295ab3346a896a4d101182b1acd

**Comment by MaksymTaratuta55** [comment]
@thecodeclimber, what do you think about this react player https://www.npmjs.com/package/react-player? I haven't used it but it seems more active and popular

**Comment by thecodeclimber** [comment]
@MaksymTaratuta55 

I received an email with a question about `react-player`.  Did you erase the comment?  Either way, that is the player I want to use :).

**Comment by MaksymTaratuta55** [comment]
@thecodeclimber, yeah, I paused the video, then asked and then resumed and found out that you advise it too. So I deleted my question :)

**Comment by thecodeclimber** [comment]
that's what I thought :).  Just wanted to make sure.  I know the video is a little long.

**Comment by thecodeclimber** [comment]
@MaksymTaratuta55 

I made a video on how I would like to rework the hero comments:  https://www.loom.com/share/adcbc4753d2f4cec85fc48f79ac976ce

Please take a look and let me know if you have any questions.

Thanks :).

**Comment by MaksymTaratuta55** [comment]
@thecodeclimber, updated
