### ISSUE TITLE
Why Do We Need Subfolders in the Theme Folders

### ISSUE THREAD

**Issue by thecodeclimber** [ramsayinnovations/ramsay-ui#7]
@MaksymTaratuta55 

Right now this is the file structure of the the `theme` folder:

```
- theme.js
- - typogrpahy
- - - typography.js
- - button
- - - button.js
- - etc.
```

Why, though, do we need these sub-folders?  Doesn't this structure make more sense:

```
- theme.js
- typography.js
- button.js
- etc.
```

**Comment by MaksymTaratuta55** [comment]
I think use folders is better. In this case, we have only 1 `theme.js` file in the `theme` folder. It is better for searching. And now I am working at the `Hero` block, so I've added:
```
- theme
- - block
- - -hero.js
- theme.js
```
So if we add a new block we'll add it to `src/theme/block/newBlock.js`. I think it is a comfortable structure.
What do you think now? Have I changed your mind?)

**Comment by thecodeclimber** [comment]
@MaksymTaratuta55 

We'll leave it as is for now and if need be revisit it in the future.

**Comment by thecodeclimber** [comment]
@MaksymTaratuta55 

That is to say -- we'll do it WITH folders for now :).
